Show better error if virtual env is broken
pypa/pipenv pull request #2595
Opened 2018-07-17 09:11 UTC by sinscary

This show better error to the user if virtual env is broken
also suggests commands to solve the issue

Closes https://github.com/pypa/pipenv/issues/1918

2018-07-17 10:20 UTC, uranusjr commented
Hi, thanks for the work! I feel the `pipenv install` part could be made more general—people don’t necessarily use it to bootstrap their environments, and generally want to specify a Python version/executable themselves. Something like “Running pipenv --rm and rebuild the virtual environment may resolve the issue” could be better, but I wonder if that is a clear enough instruction for more relatively inexperienced users. What do you think?

2018-07-17 11:15 UTC, uranusjr commented
Maybe something like “… rebuild the virtual environment, e.g. `pipenv install`”?

2018-07-17 11:17 UTC, sinscary commented
Yeah, that's also good. I will update the error message to what you suggested.

2018-07-17 11:44 UTC, uranusjr commented
I’m very bad at figuring out what is more understandable for newcomers, so I’ll leave the decision to you :) I’ll merge either way.

2018-07-18 06:38 UTC, merged

2024-01-19 08:15 UTC, Raffffqq reviewed
- [ ]

2024-01-19 08:18 UTC, Raffffqq requested changes
- > []()![IMG-20240119-WA0001.jpeg](https://github.com/pypa/pipenv/assets/150638518/ca12e1be-2b4c-4b53-9756-e5e6162bf5df)

> - @__