Add `pipenv scripts` command to list scripts in Pipfile
pypa/pipenv pull request #4445
Opened 2020-08-28 18:12 UTC by GlenRSmith

Enhancement discussed in #3686

2020-08-31 01:21 UTC, frostming commented
A news fragment is needed to notice what is new. You can place it under the `news/` directory, see the other files about how to write one.

2020-09-02 07:39 UTC, uranusjr commented
Maybe we should name this `scripts` instead for consistency. I misspelled `[scripts]` as `[script]` recently and spent almost half an hour wondering why my scripts don’t get picked up by Pipenv.

2020-09-03 00:32 UTC, uranusjr commented on tests/integration/test_cli.py
> +        assert 'pyver' in c.out
I would also test the `which python` part is also in the output.

2020-09-08 02:19 UTC, frostming requested changes
One more step before merge: add a news entry file under `news/` directory. @GlenRSmith

2020-09-08 03:42 UTC, uranusjr commented on pipenv/cli/command.py
> +    return
This return has no function.

2020-09-08 14:49 UTC, GlenRSmith commented on pipenv/cli/command.py
> +    return
Fixed.

2020-09-08 14:50 UTC, GlenRSmith commented
@frostming Added. Sorry for the omission.

2020-09-10 02:09 UTC, merged