Bug solved: creating virtual environment when not present
pypa/pipenv pull request #4780
Opened 2021-08-30 17:20 UTC by vibhutimishra

Thank you for contributing to Pipenv!

### The issue

What is the thing you want to fix? Is it associated with an issue on GitHub? Please mention it.

Yes it is associated with and issue #4537 

### The fix

Initially when virtual environment is not present it creates a virtual environment and if it is present then it removes the existing virtual environment and creates a new one if PIPENV_SITE_PACKAGES=1 is set.

I have removed this issue and added a feature which uses the existing virtual environment when present and does not remove the the existing virtual environment when PIPENV_SITE_PACKAGES=1 is set.

### The checklist

* [x]  Associated issue
* [x] A news fragment in the `news/` directory to describe this fix with the extension `.bugfix`, `.feature`, `.behavior`, `.doc`. `.vendor`. or `.trivial` (this will appear in the release changelog). Use semantic line breaks and name the file after the issue number or the PR #.

2021-11-11 06:39 UTC, melvyn-oviavo requested changes

2021-11-11 06:39 UTC, melvyn-oviavo commented on pipenv/core.py
> +                project.s.PIPENV_YES or click.confirm("Using existing virtualenv?", default=True)
(1) Using -> Use

2021-11-11 06:39 UTC, melvyn-oviavo commented on pipenv/core.py
> +        print("here")
(2) Debugging left over?

2021-11-11 06:39 UTC, melvyn-oviavo commented on pipenv/core.py
> +    if project.virtualenv_exists:
(2) This should probably be an or now:
`if project.s.PIPENV_USE_SYSTEM or project.virtualenv_exists:`

2022-01-31 21:37 UTC, oz123 commented
Obsoleted by #4936

2022-01-31 21:37 UTC, closed without merging