Prototyping a fix for: Pipenv Does Not Respect Index Specified For A Package
pypa/pipenv pull request #4983
Opened 2022-03-14 14:07 UTC by matteius

Get code changes that fix the indexes not being respected into the CI to see if any other tests are failing (locally they are in a good spot).   Acknowledged that this modifies code in pip, and so I will need extra considerations on how to proceed.   Yet without this logic, there is no way to enforce the index specifications are abided by during resolution and installation.   After several iterations of trying to understand this code and how to fix it, it feels like the `LinkCollector`''s `SearchScope` should have the knowledge it needs to return the right indexes at the right times.

### The issue
Pipenv Lock (Or Install) Does Not Respect Index Specified For A Package  https://github.com/pypa/pipenv/issues/4637

### The fix

Without this or similar logic, there is no way to enforce the index specifications are abided by during resolution and installation.   After several iterations of trying to understand this code and how to fix it, it feels like the `LinkCollector`''s `SearchScope` should have the knowledge it needs to return the right indexes at the right times.  Otherwise the pipenv resolver is totally disconnected from the pip resolver in terms of these specifications.

### The checklist

* [X] Associated issue
* [ ] A news fragment in the `news/` directory to describe this fix with the extension `.bugfix`, `.feature`, `.behavior`, `.doc`. `.vendor`. or `.trivial` (this will appear in the release changelog). Use semantic line breaks and name the file after the issue number or the PR #.

2022-03-14 14:36 UTC, matteius commented
Note:  There appears to be 1 failing test when they are run together, but that test passes in isolation.   I'll have to find more time to investigate that.
```
(pipenv) matteius@matteius-VirtualBox:~/pipenv$ python -m pytest -sv -k test_install_specifying_index_url
======================================================= test session starts ========================================================
platform linux -- Python 3.10.2, pytest-6.2.5, py-1.11.0, pluggy-1.0.0 -- /home/matteius/.virtualenvs/pipenv-wR0g04D--3.7/bin/python
cachedir: .pytest_cache
rootdir: /home/matteius/pipenv, configfile: setup.cfg, testpaths: tests
plugins: flaky-3.7.0, forked-1.3.0, xdist-2.4.0, timeout-2.0.1, pypi-0.1.1
collected 282 items / 281 deselected / 1 selected                                                                                  

tests/integration/test_install_uri.py::test_install_specifying_index_url $ pipenv install pipenv-test-private-package --index https://test.pypi.org/simple
Installing pipenv-test-private-package...
Installing dependencies from Pipfile.lock (b8219d)...
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.

Creating a virtualenv for this project...
Pipfile: /tmp/pipenv-a70hf424-project/Pipfile
Using /home/matteius/.virtualenvs/pipenv-wR0g04D--3.7/bin/python3 (3.10.2) to create virtualenv...
created virtual environment CPython3.10.2.final.0-64 in 811ms
  creator CPython3Posix(dest=/tmp/pipenv-a70hf424-project/.venv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/tmp/pipenv-2zxclxjk-test/home/.local/share/virtualenv)
    added seed packages: pip==21.3.1, setuptools==58.3.0, wheel==0.37.0
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator

Successfully created virtual environment!
Virtualenv location: /tmp/pipenv-a70hf424-project/.venv
Adding pipenv-test-private-package to Pipfile's [packages]...
Installation Succeeded
Pipfile.lock not found, creating...
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
Success!
Updated Pipfile.lock (b8219d)!

PASSED

================================================ 1 passed, 281 deselected in 21.85s ================================================
```

2022-03-14 16:28 UTC, matteius commented
I narrowed down the test failure:  specifically which other test cannot be run with the failing test, if you run this pytest command, the current suite fails and I suspect it is because both of these tests pass in `--index` and that ends up contaminating something (the tests are not fully isolated)  However if you reverse the order of these two tests they both pass, which I find very odd.
`python -m pytest -sv tests/integration/test_install_uri.py::test_install_named_index_alias tests/integration/test_install_uri.py::test_install_specifying_index_url`

2022-03-15 02:32 UTC, frostming requested changes
Need to update the patch files as well.

2022-03-15 02:40 UTC, matteius commented
> Need to update the patch files as well.

@frostming Thanks for checking on this 💯   I just opened a PR against Pip -- any idea how that group will react?  I am willing to make this into a patch but it seems like it would be better if it gets accepted upstream.   If it does not gain traction and needs to be patched instead, we might want to do it once 22.0.4 vendoring branch is merged in since the patches changed a lot between now and then.

2022-03-15 02:42 UTC, frostming commented
> it would be better if it gets accepted upstream

It isn't likely to be accepted since it isn't useful for `pip`.

2022-03-19 11:55 UTC, matteius commented
Thanks @frostming the patch file has been added.

2022-03-19 15:43 UTC, oz123 approved these changes

2022-03-22 03:57 UTC, merged