Include markers #5092
pypa/pipenv pull request #5114
Opened 2022-05-30 16:37 UTC by ImreC

@matteius @oz123 I think this is literally what needs to happen for this, after the changes that were done a month ago. Or am I overlooking something?

2022-05-30 19:52 UTC, oz123 commented
@ImreC thanks for contributing again.
I would appreciate if it, if you could include a test case and the usual news fragment.

2022-05-30 19:52 UTC, oz123 requested changes
See my other comment about test and news.

2022-05-31 07:29 UTC, ImreC commented
Yeah sure. Was just checking if this was literally it. Will do that later today

2022-06-02 05:26 UTC, matteius commented
Yeah that seems like the logical change.  @ImreC Not sure you timeline, but I'd like to do another pipenv release due to another issue in the next week or so and would love if we could include this one as well.

2022-06-07 11:47 UTC, ImreC commented
Hi @matteius, this completely fell off the map on my end. I'm having a very busy couple of weeks. I will find some time on Friday to do this

2022-06-14 07:50 UTC, ImreC commented
@oz123 @matteius I have now implemented it as an optional flag. Do you agree with this approach? Happy to make it default if that's better

2022-06-15 11:56 UTC, matteius commented
@ImreC I am thinking it should be the default behavior to include markers, but perhaps a flag like you have to exclude them (non-default) makes sense?  Especially with reports like this, having the ability to exclude markers may be relevant for some:

Also, Not sure if you saw my comment the other day I CC'd you on another issue report, the TLDR is (having trouble finding the ticket link)
> I do wonder if in the code I linked to for the requirements command, if we should have the logic first add the dev dependencies so that the production dependencies can overwrite any of those? -- that seems more correct to me than allowing the dev dependencies to break the production specifiers.

2022-06-18 22:49 UTC, oz123 commented
I tend to agree here, the flag should actually be `--exclude-markers` and the default behaviour should include them.

2022-06-24 11:13 UTC, ImreC commented
@oz123 @matteius I flipped the markers flag. I really have been short for time the last couple of weeks. Hope this covers all.

2022-06-24 11:16 UTC, matteius commented on docs/advanced.rst
> +Adding the ``--exclude-markers`` flagwill exclude the markers from the output.
typo need space `flag will`  -- I tried to edit this but I don't think I can directly without some hoop jumping.

2022-06-24 11:17 UTC, matteius commented on pipenv/cli/command.py
> +    if not dev_only:
Thanks for flipping the ordering here!

2022-06-24 11:18 UTC, matteius approved these changes
I approve @ImreC nice work -- just if you can please add the space for the typo so we can merge soon.

2022-06-24 18:22 UTC, oz123 commented
@ImreC @matteius please also fix the merge conflict.

2022-06-25 10:47 UTC, matteius commented
@oz123 I am not seeing what you mean by a potential merge conflict ... If there is not one, I am ready to merge this and will push a commit to main to fix the documentation typo.

2022-06-25 11:21 UTC, oz123 commented
Ay! Sorry depending on the type of merge, there will be a conflict or there won't be.
![image](https://user-images.githubusercontent.com/1083045/175771292-f056b14d-c5ce-4401-9cee-206dcb978dc8.png)

![image](https://user-images.githubusercontent.com/1083045/175771306-5e3e29d9-3ee0-49c6-85eb-e646028568d2.png)

2022-06-25 11:23 UTC, merged