Allow more --system operations in pipenv
pypa/pipenv pull request #5144
Opened 2022-06-24 10:37 UTC by matteius

### The issue

We get a lot of issue reports about how pipenv cannot be used at the system level, which is actually quite common in Docker containers for people to want to bypass the virtualenv construct entirely.  

#5052 
#5115 5115

### The fix

I am still prototyping this and I suspect tests will need adjustment, but this allowed me to do `pipenv install requests --system`
which generated this Pipfile:
```
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
requests = "*"

[dev-packages]

[requires]
python_version = "3.9"
```
And Pipfile.lock:
```
{
    "_meta": {
        "hash": {
            "sha256": "b8c2e1580c53e383cfe4254c1f16560b855d984fde8b2beb3bf6ee8fc2fe5a22"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.9"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "certifi": {
            "hashes": [
                "sha256:84c85a9078b11105f04f3036a9482ae10e4621616db313fe045dd24743a0820d",
                "sha256:fe86415d55e84719d75f8b69414f6438ac3547d2078ab91b67e779ef69378412"
            ],
            "markers": "python_version >= '3.6'",
            "version": "==2022.6.15"
        },
        "charset-normalizer": {
            "hashes": [
                "sha256:2857e29ff0d34db842cd7ca3230549d1a697f96ee6d3fb071cfa6c7393832597",
                "sha256:6881edbebdb17b39b4eaaa821b438bf6eddffb4468cf344f09f89def34a8b1df"
            ],
            "markers": "python_version >= '3.5'",
            "version": "==2.0.12"
        },
        "idna": {
            "hashes": [
                "sha256:84d9dd047ffa80596e0f246e2eab0b391788b0503584e8945f2368256d2735ff",
                "sha256:9d643ff0a55b762d5cdb124b8eaa99c66322e2157b69160bc32796e824360e6d"
            ],
            "markers": "python_version >= '3.5'",
            "version": "==3.3"
        },
        "requests": {
            "hashes": [
                "sha256:bc7861137fbce630f17b03d3ad02ad0bf978c844f3536d0edda6499dafce2b6f",
                "sha256:d568723a7ebd25875d8d1eaf5dfa068cd2fc8194b2e483d7b1f7c81918dbec6b"
            ],
            "index": "pypi",
            "version": "==2.28.0"
        },
        "urllib3": {
            "hashes": [
                "sha256:44ece4d53fb1706f667c9bd1c648f5469a2ec925fcf3a776667042d645472c14",
                "sha256:aabaf16477806a5e1dd19aa41f8c2b7950dd3c746362d7e3223dbe6de6ac448e"
            ],
            "markers": "python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3, 3.4' and python_version < '4'",
            "version": "==1.26.9"
        }
    },
    "develop": {}
}
```

### The checklist
* [X] Associated issue
* [ ] A news fragment in the `news/` directory to describe this fix with the extension `.bugfix`, `.feature`, `.behavior`, `.doc`. `.vendor`. or `.trivial` (this will appear in the release changelog). Use semantic line breaks and name the file after the issue number or the PR #.

2022-06-24 12:55 UTC, matteius commented
Amazingly zero tests broke by removing that validation crud. 
TODO -- Check on the exception classes that were being raised if they are still being used anywhere.
TODO -- Solve for this doesn't work if `--deploy` flag is also passed, possibly, need to check this.

2022-06-25 11:40 UTC, oz123 commented
I think removing this break lever is OK for docker containers. I would not like to see people complaining here that pipenv broke their system. Hence, I suggest:
If people do use this flag, I want to see a color prompt telling them to type `YES` after a warning that this could break their system.
If people use docker, they should set an environment variable `PIPENV_USE_SYSTEM_PYTHON` which allows overriding this prompt.

This should be documented properly:
In the environment variables section.
In the section of using pipenv with docker.

2022-06-25 11:40 UTC, oz123 requested changes

2022-06-25 11:40 UTC, oz123 commented on pipenv/core.py
> +            crayons.normal(fix_utf8("Pipfile.lock not found, creating..."), bold=True),
Please use  `click.secho` here. So we can finally remove crayons.

2023-04-21 02:24 UTC, fchenGT commented
Somehow, this didn't work for me and get the same error message:
```dockerfile
# Install dependencies from Pipfile
COPY ${SOURCE_DIRECTORY}/Pipfile.lock .

RUN pip install pipenv==2023.4.20 && \
    pipenv sync --system && \
    pip uninstall --yes pipenv
```

but this works for me:
```dockerfile
# Install dependencies from Pipfile
COPY ${SOURCE_DIRECTORY}/Pipfile .
COPY ${SOURCE_DIRECTORY}/Pipfile.lock .

RUN pip install pipenv==2023.4.20 && \
    pipenv sync --system && \
    pip uninstall --yes pipenv
```

What is strange is "pipenv sync" should only need Pipefile.lock to work, but when building a docker image that wasn't the case.

2023-08-26 13:04 UTC, oz123 commented
This PR is stale and has to be redone.

2023-08-26 13:04 UTC, closed without merging