Add Python 3.11 release candidate to the testing
pypa/pipenv pull request #5245
Opened 2022-08-13 14:17 UTC by cclauss

Thank you for contributing to Pipenv!

### The issue

What is the thing you want to fix? Is it associated with an issue on GitHub? Please mention it.

Always consider opening an issue first to describe your problem, so we can discuss what is the best way to amend it.  Note that if you do not describe the goal of this change or link to a related issue, the maintainers may close the PR without further review.

If your pull request makes a non-insignificant change to Pipenv, such as the user interface or intended functionality, please file a PEEP.

    https://github.com/pypa/pipenv/blob/master/peeps/PEEP-000.md

### The fix

How does this pull request fix your problem? Did you consider any alternatives? Why is this the *best* solution, in your opinion?

### The checklist

* [ ] Associated issue
* [ ] A news fragment in the `news/` directory to describe this fix with the extension `.bugfix`, `.feature`, `.behavior`, `.doc`. `.vendor`. or `.trivial` (this will appear in the release changelog). Use semantic line breaks and name the file after the issue number or the PR #.

2022-09-08 16:48 UTC, cclauss commented
https://github.com/pypa/pipenv/pull/5343#issuecomment-1240825697

2022-10-25 08:22 UTC, cclauss commented
* [x] `vendor.txt: Upgrade to attrs==22.1.0`
* [ ] Where is the version of pytest specified?

2022-10-25 10:19 UTC, edmorley commented
For `attr`, I believe the vendored copy needs updating by running the command mentioned here:
https://github.com/pypa/pipenv/blob/main/pipenv/vendor/README.md

> Where is the version of pytest specified?

I'm guessing it's maybe pulled in implicitly via one of the `pytest-*` deps here?
https://github.com/pypa/pipenv/blob/cb9d87ad05830449743cbc3ffa09ebbc7cca602d/Pipfile#L6-L21

Maybe refreshing this repo's `Pipfile.lock` will be sufficient to pick up the 7.2.0 update?

2022-11-05 19:53 UTC, edmorley commented
@cclauss Several vendored dependencies (including `attr`) have now been updated on `main`. Could you rebase on `main` to pick up those changes? After that, I would recommend running `pipenv lock` to refresh this repo's `Pipfile.lock`, since hopefully the pytest update will resolve the other issues :-)

2022-11-08 11:33 UTC, edmorley commented
@oz123 HI! I don't suppose you have a spare moment to review/merge this? :-)

2022-11-08 18:17 UTC, oz123 requested changes

2022-11-08 18:28 UTC, cclauss commented on Pipfile.lock
>          },
https://github.com/pypa/pipenv/pull/5245#issuecomment-1304622593

2022-11-08 18:31 UTC, merged