Address Issue #5129: Document how to rename (move) project directory
pypa/pipenv pull request #5824
Opened 2023-08-06 00:46 UTC by langaa-egeskov

### The issue:  Document how to rename or move a project directory
I was helped by the answer in issue #5123 and the further guidance in issue #5129 

### The fix: Added to existing documentation in 2 places
- Added documentation in installation.md under 'Virtualenv' mapping caveat
- Added documentation to the virtualenv.md

This is my first pull request so feedback very welcome.

### The checklist

* [X ] Associated issue
* [ X] A news fragment in the `news/` directory to describe this fix with the extension `.bugfix.rst`, `.feature.rst`, `.behavior.rst`, `.doc.rst`. `.vendor.rst`. or `.trivial.rst` (this will appear in the release changelog). Use semantic line breaks and name the file after the issue number or the PR #.

2023-08-07 17:55 UTC, oz123 requested changes
Thanks for your contribution. Only a minor request for a change.

2023-08-07 17:55 UTC, oz123 commented on news/5129.doc.rst
> +- Added documentation on how to move or rename a project directory
Please remove leading `-`.

2023-08-10 22:14 UTC, langaa-egeskov commented
Sorry, I don't mean to leave this hanging.  I'm working on resolving why the code linting and ruff tests are failing and I haven't figured it out yet.

2023-08-11 01:59 UTC, matteius commented
@IamAdiSri the ruff tests are a new issue because it keeps introducing new rules or inspecting new files -- it also happened on my draft-no-reqslib PR ... don't worry about it, just fix the main lint of the CI job and you'll be good.

2023-08-11 02:00 UTC, matteius commented
You can try running: `pre-commit run --all-files --verbose --show-diff-on-failure --fix` for the CI issue preventing your build.

2023-08-13 21:06 UTC, langaa-egeskov commented
thanks for the help! on my machine tests ran and  seems sucessful
<img width="650" alt="image" src="https://github.com/pypa/pipenv/assets/14239246/202e5d3d-14ec-4d76-86f5-b706ef8df0d9">

2023-08-17 20:21 UTC, oz123 commented
All the failures that ruff reports have nothing to do with the PR.

2023-08-17 20:21 UTC, merged

2023-08-17 20:21 UTC, oz123 reviewed
Thank you for your contribution.