Corrected behavior of uninstall --all
pypa/pipenv pull request #6209
Opened 2024-07-29 01:41 UTC by matteius

Thank you for contributing to Pipenv!

### The issue

When I recently refactored the uninstall command behavior to be smarter, I broke the expected behavior of `--all` flag.

Fixes #6200 

### The checklist

* [X] Associated issue
* [ ] A news fragment in the `news/` directory to describe this fix with the extension `.bugfix.rst`, `.feature.rst`, `.behavior.rst`, `.doc.rst`. `.vendor.rst`. or `.trivial.rst` (this will appear in the release changelog). Use semantic line breaks and name the file after the issue number or the PR #.

2024-07-29 16:40 UTC, dan-hook requested changes
Thanks for looking into this.

2024-07-29 16:40 UTC, dan-hook commented on pipenv/routines/uninstall.py
> +            # Remove the packages from the Pipfile
I can't verify that this comment is accurate for what the code is doing, but removing the packages from the Pipfile is exactly what we don't want to do during uninstall --all to be consistent with the documented behavior.  

There was a test changed in a previous PR that should be reverted:  https://github.com/pypa/pipenv/pull/6029#discussion_r1674707464
If the test as it currently stands is passing, then uninstall --all isn't working like it used to.

2024-08-23 15:04 UTC, dan-hook approved these changes

2024-08-25 13:26 UTC, matteius commented on tests/integration/test_uninstall.py
> -        assert p.pipfile["dev-packages"] == {}
I think I need to revert this part of the PR -- while it doesn't make sense to me in terms of the code paths that --all-dev does something different than --all, I guess it does.

2024-08-31 21:46 UTC, merged