Check end of path for shell detection
pypa/pipenv pull request #6212
Opened 2024-07-29 21:48 UTC by JoshStern

Thank you for contributing to Pipenv!

### The issue
Shell detection checks the entire path when looking for shell substrings. This can cause the wrong branch to get tripped if shells are installed in a path with another shell in the tree. In my case a `li[nu]xbrew`-installed `zsh` goes down the `nu` shell path.

### The fix

This updates the check to only look at the end of `cmd` when detecting shells.

### The checklist

* [x] Associated issue: #6197 
* [x] A news fragment in the `news/` directory to describe this fix with the extension `.bugfix.rst`, `.feature.rst`, `.behavior.rst`, `.doc.rst`. `.vendor.rst`. or `.trivial.rst` (this will appear in the release changelog). Use semantic line breaks and name the file after the issue number or the PR #.

2024-07-30 20:10 UTC, oz123 requested changes
Actually, I prefer this over the split over `.linuxbrew`.
This solution will cause future maintainers to raise eyebrows and wrinkle their foreheads trying to figure it out without reading the original issue.

This approach is much more maintainable. However, I have a small suggestion:

Change:

```
cmd.endswith("<shell name>")
```
to:
```
cmd.endswith("/<shell name>"):
```

This will allow to for shortcutting the if ...elif at the head in favor of the most common shells (bash, zsh, sh):

```
if cmd.endswith("/sh","/bash","/zsh")":
   suffix = ""
  command = "."
elif cmd.endswith("/csh"):
  ...
  
else:
     raise ValueError("unknown shell ...") ....
```

This works for all three:
```
>>> cmd="/bin/sh"
>>> cmd.endswith(("/bash","/zsh", "/sh"))
True
>>> cmd="/bin/zsh"
>>> cmd.endswith(("/bash","/zsh", "/sh"))
True
>>> cmd="/bin/bash"
>>> cmd.endswith(("/bash","/zsh", "/sh"))
True
>>> 
```

2024-07-30 20:13 UTC, oz123 commented
@JoshStern thank you for your effort so far (immediately adding news file, is great! ).

I gave your PR some consideration and I think that your solution is better than what I initially suggested.
Adding a shortcut for the most common shells is only possible with your approach.

2024-07-30 20:39 UTC, JoshStern commented
@oz123 updated! Thank you for the feedback and quick turnaround.

2024-07-30 21:01 UTC, oz123 commented
Yes. Please. The zsh, bash and sh bash should be at the top. Unknown shells should not fall silently to imaginary default. They should raise exceptions.

2024-07-30 21:47 UTC, JoshStern commented
Updated, I'm a little concerned about other `sh` or `bash` compatible shells out there that will get sent down the ValueError branch. `ksh` comes to mind.

2024-07-31 08:44 UTC, closed without merging

2024-07-31 08:44 UTC, oz123 commented
Thanks! I merged your commits with one on top!

2024-07-31 13:23 UTC, JoshStern commented
Thank you for the help with this! Glad I could contribute 😄